import '../styles/globals.css';

import Footer from './_components/_layout/Footer';
import { Inter } from 'next/font/google';
import RootLayoutClient from './layoutClient';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: '더취페이',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <RootLayoutClient>{children}</RootLayoutClient>
        <Footer />
      </body>
    </html>
  );
}
