import '../styles/globals.css';

import Footer from './_components/Footer';
import { Inter } from 'next/font/google';
import RootLayoutClient from './layoutClient'; // 클라이언트 컴포넌트 가져오기

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: '더취페이',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <RootLayoutClient>{children}</RootLayoutClient> {/* 클라이언트 컴포넌트로 감싸기 */}
        <Footer />
      </body>
    </html>
  );
}
