import '@/styles/globals.css';

import RootLayoutClient from './layoutClient';

export const metadata = {
  title: '더취페이',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <RootLayoutClient>{children}</RootLayoutClient>
      </body>
    </html>
  );
}
