import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: '로그인',
  description: 'Generated by create next app',
};

export default function Layout({ children }) {
  return <div>{children}</div>;
}
